import React from "react";
import ChinaPneumoniaAir from "../../echarts/charts/ChinaPneumoniaAir"
class pdfFour extends React.Component {
    render() {
        const ChinaPneumoniaAir1 = {
            id: 'ChinaPneumoniaAir1n',
            height: '600px',
            outname: [
                '南海诸岛',
                '北京',
                '天津',
                '上海',
                '重庆',
                '河北',
                '河南',
                '云南',
                '辽宁',
                '黑龙江',
                '湖南',
                '安徽',
                '山东',
                '新疆',
                '江苏',
                '浙江',
                '江西',
                '湖北',
                '广西',
                '甘肃',
                '山西',
                '内蒙古',
                '陕西',
                '吉林',
                '福建',
                '贵州',
                '广东',
                '青海',
                '西藏',
                '四川',
                '宁夏',
                '海南',
                '台湾',
                '香港',
                '澳门',
            ],
            outvalue: [
                1,
                524,
                13,
                140,
                75,
                13,
                83,
                11,
                19,
                15,
                69,
                260,
                39,
                4,
                31,
                104,
                36,
                1052,
                33,
                347,
                9,
                157,
                22,
                4,
                18,
                5,
                2398,
                41,
                0,
                484,
                404,
                22,
                3,
                5,
                225,
            ],
        };
        const ChinaPneumoniaAir2 = {
            id: 'ChinaPneumoniaAir1m',
            height: '600px',
            outname: [
                '南海诸岛',
                '北京',
                '天津',
                '上海',
                '重庆',
                '河北',
                '河南',
                '云南',
                '辽宁',
                '黑龙江',
                '湖南',
                '安徽',
                '山东',
                '新疆',
                '江苏',
                '浙江',
                '江西',
                '湖北',
                '广西',
                '甘肃',
                '山西',
                '内蒙古',
                '陕西',
                '吉林',
                '福建',
                '贵州',
                '广东',
                '青海',
                '西藏',
                '四川',
                '宁夏',
                '海南',
                '台湾',
                '香港',
                '澳门',
            ],
            outvalue: [
                1,
                524,
                13,
                140,
                75,
                13,
                83,
                11,
                19,
                15,
                69,
                260,
                39,
                4,
                31,
                104,
                36,
                1052,
                33,
                347,
                9,
                157,
                22,
                4,
                18,
                5,
                2398,
                41,
                0,
                484,
                404,
                22,
                3,
                5,
                225,
            ],
        };
        const ChinaPneumoniaAir3 = {
            id: 'ChinaPneumoniaAir1mn',
            height: '600px',
            outname: [
                '南海诸岛',
                '北京',
                '天津',
                '上海',
                '重庆',
                '河北',
                '河南',
                '云南',
                '辽宁',
                '黑龙江',
                '湖南',
                '安徽',
                '山东',
                '新疆',
                '江苏',
                '浙江',
                '江西',
                '湖北',
                '广西',
                '甘肃',
                '山西',
                '内蒙古',
                '陕西',
                '吉林',
                '福建',
                '贵州',
                '广东',
                '青海',
                '西藏',
                '四川',
                '宁夏',
                '海南',
                '台湾',
                '香港',
                '澳门',
            ],
            outvalue: [
                1,
                524,
                13,
                140,
                75,
                13,
                83,
                11,
                19,
                15,
                69,
                260,
                39,
                4,
                31,
                104,
                36,
                1052,
                33,
                347,
                9,
                157,
                22,
                4,
                18,
                5,
                2398,
                41,
                0,
                484,
                404,
                22,
                3,
                5,
                225,
            ],
        };
        return (
            <div>
                <ChinaPneumoniaAir {...ChinaPneumoniaAir1} />
                <ChinaPneumoniaAir {...ChinaPneumoniaAir2} />
                <ChinaPneumoniaAir {...ChinaPneumoniaAir3} />
            </div>
        )
    }
}
export default pdfFour;